### ISSUE TITLE
About Test

### ISSUE THREAD

**Issue by Selen-Suyue** [yangbincv/SDCL#3]
I've trained the model as you required. However when I test, the "torch.load" could not load the model end with '.tar'. How can I cope with the problem?

**Comment by yangbincv** [comment]
What error was reported?

**Comment by Selen-Suyue** [comment]
PytorchStreamReader failed reading zip archive

**Comment by yangbincv** [comment]
We did not find the error during our testing. Is it because of the version of the environment

**Comment by Selen-Suyue** [comment]
thannk u!
